### ISSUE TITLE
Yaml library is now unmaintained

### ISSUE THREAD

**Issue by AmberArcadia** [chainguard-dev/yam#108]
See https://github.com/go-yaml/yaml?tab=readme-ov-file#this-project-is-unmaintained

Perhaps this is our opportunity to refactor to a new library, and fix some bugs caused by the old one.

**Comment by StevenACoffman** [comment]
BTW, since this issue, there's been some news that you are probably aware of.

+[yaml/go-yaml](https://github.com/yaml/go-yaml) is the new yaml org maintained fork of the unmaintained [go-yaml/yaml](https://github.com/go-yaml/yaml) repo.
+ [Kubernetes KEP proposal to adopt KYAML subset with formatter](https://github.com/kubernetes/enhancements/blob/master/keps/sig-cli/5295-kyaml/README.md)

While I have used `yam`, I've also used `github.com/google/yamlfmt/cmd/yamlfmt` combined with a Go installed wasi compiled version of the python yamllint https://github.com/wasilibs/go-yamllint so I don't need to mess with Python venvs (although astral's uv now makes that less awful).

```bash
#!/bin/bash

# see https://til.simonwillison.net/yaml/yamlfmt

function is_bin_in_path {
  builtin type -P "$1" &> /dev/null
}

export GOBIN="$HOME/go/bin"
! is_bin_in_path yamlfmt && GOBIN=$HOME/go/bin go install -v github.com/google/yamlfmt/cmd/yamlfmt@latest

# -formatter indentless_arrays=true,retain_line_breaks=true
yamlfmt \
  -conf .yamlfmt.yaml .
```
With a .yamlfmt.yaml file like:
```yaml
# yamlfmt is an extensible command line tool or library to format yaml files.
#
# Get it from: https://github.com/google/yamlfmt/releases
# Config is here: https://github.com/google/yamlfmt/blob/main/docs/config-file.md
formatter:
  type: basic
  indentless_arrays: true
indent: 2
line_ending: lf
```

And my Yamlint: 
```
extends: default
rules:
  braces: disable
  brackets: disable
  colons: enable
  commas: disable
  comments: disable
  comments-indentation: disable
  document-end: disable
  document-start: disable
  empty-lines: disable
  empty-values: disable
  hyphens: enable
  indentation:
    spaces: 2
    check-multi-line-strings: false
    indent-sequences: false
  key-duplicates: enable
  key-ordering: disable
  line-length: disable
  new-line-at-end-of-file: disable
  new-lines: enable
  octal-values: disable
  quoted-strings: disable
  trailing-spaces: disable
  truthy:
    allowed-values: ['true', 'false', 'on'] # 'on' for GH action trigger annoyingly
    check-keys: false
```
