### ISSUE TITLE
Alphabetize packages by convention, update existing modules, and validate

### ISSUE THREAD

**Issue by vaikas** [chainguard-dev/yam#27]
It would be nice to have packages alphabetized so it's easier to find if a particular package is there or not visually. Add verbiage saying this is the convention, update existing packages (this could be done lazily), add a presubmit check to enforce this.

**Comment by luhring** [comment]
Awesome idea! I love it.

Since `yam` operates on YAML generically, we could have an implementation that's generic. Maybe something like "**_sort_** path expressions", similar to how today you can specify "**_gap_** path expressions", where matching YAML elements have their child elements gapped with empty lines.

E.g. given a file `foo.yaml`:

```yaml
name: ville
favorite-dans:
  - luhring
  - lorenc
```

You could run `yam --sort '.favorite-dans' foo.yaml` (or the equivalent via a yam config file) to produce:

```yaml
name: ville
favorite-dans:
  - lorenc
  - luhring
```

(Which would hurt my feelings, but at least sorted alphabetically...)

WDYT?
