### ISSUE TITLE
Anchor syntax incorrectly formatted

### ISSUE THREAD

**Issue by xnox** [chainguard-dev/yam#43]
yaml files with anchors are not correctly formatted.

**Comment by luhring** [comment]
@xnox thanks! any chance you could add an example? Like steps to reproduce and how that differs from what we want it to look like?

**Comment by shyim** [comment]
Running yam on following YAML

```
public: &public_bucket
    type: "amazon-s3"
    url: "%env(CDN_URL)%"
    visibility: "public"
    config:
        bucket: "%env(AWS_PUBLIC_FILESYSTEM_BUCKET)%"
        region: "%env(AWS_REGION)%"
        endpoint: "%env(AWS_ENDPOINT_URL)%"
        use_path_style_endpoint: true

theme: *public_bucket
asset: *public_bucket
```

generates invalid yaml to:

```
public:
  type: "amazon-s3"
  url: "%env(CDN_URL)%"
  visibility: "public"
  config:
    bucket: "%env(AWS_PUBLIC_FILESYSTEM_BUCKET)%"
    region: "%env(AWS_REGION)%"
    endpoint: "%env(AWS_ENDPOINT_URL)%"
    use_path_style_endpoint: true
theme:
*public_bucket
asset:
*public_bucket
```
