### ISSUE TITLE
formatting breaks yaml anchors

### ISSUE THREAD

**Issue by shyim** [chainguard-dev/yam#46]
Running yam on following YAML

```
public: &public_bucket
    type: "amazon-s3"
    url: "%env(CDN_URL)%"
    visibility: "public"
    config:
        bucket: "%env(AWS_PUBLIC_FILESYSTEM_BUCKET)%"
        region: "%env(AWS_REGION)%"
        endpoint: "%env(AWS_ENDPOINT_URL)%"
        use_path_style_endpoint: true

theme: *public_bucket
asset: *public_bucket
```

generates invalid yaml to:

```
public:
  type: "amazon-s3"
  url: "%env(CDN_URL)%"
  visibility: "public"
  config:
    bucket: "%env(AWS_PUBLIC_FILESYSTEM_BUCKET)%"
    region: "%env(AWS_REGION)%"
    endpoint: "%env(AWS_ENDPOINT_URL)%"
    use_path_style_endpoint: true
theme:
*public_bucket
asset:
*public_bucket
```
