### ISSUE TITLE
feature: list formatting

### ISSUE THREAD

**Issue by wlynch** [chainguard-dev/yam#62]
For some fields (like `update.exclude comment`) we may include list for details comments e.g.

```
1. ...
2. ...
3. ...
```

or 

```
- ...
- ...
- ...
```

Currently yam doesn't know how to handle these, because it treats them as a gap-less multiline string, and ends up collapsing these into a single line. Really we want to treat this more like markdown and preserve this whitespace.

**Comment by luhring** [comment]
Hey there — I'm not quite following the scenario yet... do you have an example file on hand where we could reproduce what you're seeing? There are a few known bugs with the underlying `go-yaml` library regarding comment handling, so curious if it's one of those, or if it's something we have more control over in yam itself 🤞

**Comment by wlynch** [comment]
Sure! So this config:

```yaml
update:
  enabled: true
  exclude-reason: >
    blah blah blah

    1. a
    2. b
    3. c

    asdf
```

with this config:

```yaml
gap:
  - "."
  - ".subpackages"
  - ".data"
  - ".pipeline"
  - ".update.exclude-reason"

indent: 2
```

becomes:

```yaml
update:
  enabled: true
  exclude-reason: >
    blah blah blah

    1. a 2. b 3. c

    asdf
```
