### ISSUE TITLE
Please supported mixed mode values

### ISSUE THREAD

**Issue by xnox** [chainguard-dev/yam#73]
If one specifies that something should be a string, please encode it in the most natural and deterministic way.

Example for something desired to be formatted as a list of strings please ensure that all form of canonical integer and floating point numbers are encoded as strings.

https://yaml.org/spec/1.2.2/#24-tags

Lists

```
canonical: 12345
decimal: +12345
octal: 0o14
hexadecimal: 0xC
canonical: 1.23015e+3
exponential: 12.3015e+02
fixed: 1230.15
negative infinity: -.inf
not a number: .nan
```

As valid representations of numbers, which upon parsing will not be strings. And thus need to be quoted to be strings.

For the purpose of melange, we can encounter something like "1.23015e+3" as a string value represetting package version or text git tag. But most commonly it is software with single major or single minor version only that can get miss-parsed.

**Comment by luhring** [comment]
I'm not sure I'm following what this issue is asking for yet... Are you saying that yam is mishandling YAML tags then they're specified? Are you saying that yam should define its own default behavior for when no tag is present in the input?

An example input and expected output would go a long way here! Thanks!

**Comment by xnox** [comment]
@luhring 

When doing yam on glibc.yaml I would like it to convert

```yaml
package:
  name: glibc
  version: 2.40
  epoch: 3
  description: "the GNU C library"
  copyright:
    - license: LGPL-2.1-or-later
  resources:
    cpu: 16
    memory: 16Gi
```

to

```yaml
package:
  name: glibc
  version: "2.40"
  epoch: 3
  description: "the GNU C library"
  copyright:
    - license: LGPL-2.1-or-later
  resources:
    cpu: 16
    memory: 16Gi
```

As version is a string, epoch is an integer, and cpu is an integer, and memory is unambiguous string.
